### ISSUE TITLE
User information file unwritable after installing globally

### ISSUE THREAD

**Issue by emiellr** [BartLunenborg/ThemisCli#1]
On linux it's required to use root privileges in order to install NodeJS packages globally. That also means that the `user.txt` file is not writable by normal users. When logging in using `themis login [username]`, the following error is produced:
```
themis user <username>

Set the username used for logging in.

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: EACCES: permission denied, open '/usr/lib/node_modules/themis_cli/bin/user.txt'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1209:14)
    at async Object.handler (/usr/lib/node_modules/themis_cli/bin/index.js:17:7) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/node_modules/themis_cli/bin/user.txt'
}
```
I suggest that the login info be saved in `~/.config/themis_cli/user.txt` with proper privileges.

**Comment by BartLunenborg** [comment]
Hi @emiellr 
I have not been able to replicate the issue you're encountering.
However, I agree that the save location you're suggesting is probably better and more logical.
I'll look into it.
- Bart
